mozilla-services/guardian-vpn-windows

test/integrations/integration_test.go
ui/src/ProductConstants.cs
ui/src/WCF/Tester.cs

In order to avoid IPv4/IPv6 confusion within the CI process, we should stick with 127.0.0.1 for now.

test: Replaced instances of 'localhost' with '127.0.0.1'

---

ui/src/UI/Resources/Localization/Translations/de.ftl
ui/src/UI/Resources/Localization/Translations/en-us.ftl
ui/src/UI/Views/UpdateView.xaml.cs
ui/src/UIUpdaters/VersionUpdater.cs
ui/src/Update/Update.cs
ui/src/Update/UpdateHttpClient.cs
ui/src/WCF/Service.cs
ui/src/WireGuard/Broker.cs

Fixed issue where MSI upgrade would trigger a restart, added error message displaying a clear reason why the update failed when the cause is georestrictions, removed caching within the updater httpClient.

UI: Fixed issue where MSI upgrade would trigger a restart

---

ui/src/UI/Views/ConnectionView.xaml.cs

Previously, when the user is unprotected, the client automatically initiates a connection when a server is selected, which isn't intuitive.  With this change, in the same scenario, selecting a server will return them to the main view, where the user must click the connection toggle to connect to the server.

UI: removed auto-connection on initial server selection from the connection view.

---

.circleci/config.yml
.gitignore
test/comment/index.js
test/comment/package-lock.json
test/comment/package.json
test/logger/SALogger.cs
test/logger/packages.config
test/ringloggerParser/App.config
test/ringloggerParser/Properties/AssemblyInfo.cs
test/ringloggerParser/Ringlogger.cs
test/ringloggerParser/RingloggerParser.cs
test/ringloggerParser/RingloggerParser.csproj
test/ringloggerParser/RingloggerParser.csproj.user

As we are using StyleCop Anyalyzer to lint C# code, we want to show warnings and errors in the last committed files for every PR request. We create a customized logger "SALogger" to log warnings and errors in last committed files instead of all files in the whole project. After we get the logs, we send it back to PR as comments. Meanwhile, we added a RingloggerParser to parse log file (log.bin) to txt format which can be readable.

test: Create customized logger to log warnings and errors on committed files

---

ui/src/UI/Views/Onboarding/OnboardingView1.xaml
ui/src/UI/Views/Onboarding/OnboardingView1.xaml.cs
ui/src/UI/Views/Onboarding/OnboardingView2.xaml
ui/src/UI/Views/Onboarding/OnboardingView2.xaml.cs
ui/src/UI/Views/Onboarding/OnboardingView3.xaml
ui/src/UI/Views/Onboarding/OnboardingView3.xaml.cs

When the skip button on one of the onboarding screens is clicked, the client will navigate to the last onboarding screen, where the user will be able to initiate the login flow.

ui: Modify skip button behaviour on onboarding views.

---

ui/src/UI/Views/MainView.xaml

Remove hover state from the card in the main view because users expect to be able to click components that have a hover state.  Currently, the only clickable element on the card is the toggle button, but not the card itself.

ui: Remove hover state from card in main view.

---

ui/src/UI/Components/VPNToggle/VPNToggle.xaml

Add hand cursor to VPN toggle hover state to be consistent with Windows design standards.  The mouse pointer should provide a visual indicator when moused over a focusable element.

ui: Add hand cursor to VPN toggle hover state.

---

tunnel/main.go
ui/src/Manager.cs
ui/src/Network/CaptivePortalDetection.cs
ui/src/Network/WlanWatcher.cs
ui/src/ProductConstants.cs
ui/src/UIUpdaters/ConnectionStatusUpdater.cs
ui/src/WireGuard/IPC/IPCCommand.cs
ui/src/WireGuard/IPC/IPCHandlers.cs

This feature is a settings option for a Windows notification when
connectivity issues due to a captive portal is detected. Detection of a
captive portal is determined by adding a route and sending a GET request
to a specified IP address by calling
`CaptivePortalDetection.TestOutsideConnectivity` from the broker
process. When a captive portal is detected, a Windows notification will
be displayed, prompting the user to turn off their VPN and enter login
credentials for the captive portal before re-enabling their VPN.

ui: Add captive portal detection feature

---

ui/src/FxA/Login.cs

Upon login authentication, the client will bring the main window to the
front automatically, allowing the user to continue with the post-login
flow.

ui: Bring window to front when login authentication is complete

---

ui/src/UIUpdaters/ConnectionStatusUpdater.cs
ui/src/ViewModels/MainWindowViewModel.cs
ui/src/WireGuard/Connector.cs

For connection transition states (connecting, disconnecting, switching),
there will be a minimum UI delay (1s, 1s, 1.5s respectively) before
changing to non-transition states (unprotected, protected).

ui: Add minimum visual delays for connection transition states

---

ui/src/FxA/ServerList/ServerList.cs

When the application is run for the first time, the default server will be the first server in the USA, instead of the first Austrailian server.

ui: Modify initial default server to first USA server

---

.circleci/config.yml
.gitignore
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest.sln
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/BrowserSession.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/FirefoxPrivateVPNSession.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest.csproj
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/LandingScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/LayoutScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Properties/AssemblyInfo.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/SignInScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/app.config
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/packages.config
test/smoke/aws/create_ec2.ps1
test/smoke/aws/logon.ps1
test/smoke/aws/template.json
test/smoke/aws/terminate_ec2.ps1

In order to do smoke test, we need to simulate the real production environment which is in Windows 10. However the CircleCI is current using Windows server 2019 for all windows job and Windows server 2019 only has IE 11 installed. IE 11 is not supported by FxA anymore and cannot show user login web page properly. This is why we start using VM to do smoke test.

test: set up AWS ec2 to do smoke test

---

test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Sessions/BrowserSession.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Sessions/FirefoxPrivateVPNSession.cs
test/smoke/aws/template.json
test/smoke/aws/terminate_ec2.ps1

There are a few bugs on UI tests. One of them is that the pipeline is not able to terminate the Cloudformation stack because Remove-CFNStack command needs user to confirm before terminating. The others are tests related such as maximized browser hide the UI of the vpn client and notification chevron is not auto closed on vm.

test: fix the bug on UI tests

---

.circleci/config.yml
installer/FirefoxPrivateNetworkVPN.wxs
ui/src/App.xaml.cs
ui/src/Firefox Private Network.csproj
ui/src/Firefox Private Network.csproj.user
ui/src/FxA/Account.cs
ui/src/Main.cs
ui/src/Manager.cs
ui/src/ProductConstants.cs
ui/src/UI/Resources/Localization/Translations/de.ftl
ui/src/UI/Resources/Localization/Translations/en-us.ftl
ui/src/UIUpdaters/ConnectionStatusUpdater.cs
ui/src/Update/Update.cs
ui/src/WCF/Service.cs
ui/src/Windows/Kernel32.cs
ui/src/WireGuard/Broker.cs
ui/src/WireGuard/BrokerService.cs
ui/src/WireGuard/IPC/IPC.cs
ui/src/WireGuard/IPC/IPCCommand.cs
ui/src/WireGuard/IPC/IPCHandlers.cs
ui/src/WireGuard/Tunnel.cs

After some discussion, it has been decided to refactor our current methods for elevating processes.
Elevation will always be required, but prompting the user to do so every time is a nuisance. This PR addresses that by creating an always-on elevated service listening for requests and executes basic commands pertaining to bringing up/down the tunnel, as well as retrieving the latest tunnel connection info. This service is started after the MSI installation process completes.
We have not yet determined what will the permissions look like for interacting with this service, as multiple users on the same machine may have a need for controlling the tunnel. For the time being, it's a free for all. We will determine what's the best course of action before next release.

ui/tunnel/service: Broker service refactor

---

test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Sessions/FirefoxPrivateVPNSession.cs
ui/src/Manager.cs
ui/src/NotificationArea/Tray.cs
ui/src/UI/Resources/Localization/TranslationService.cs
ui/src/UI/Resources/Localization/Translations/de.ftl
ui/src/UI/Resources/Localization/Translations/en-us.ftl
ui/src/UIUpdaters/ConnectionStatusUpdater.cs

The tray context menu was missing some localization functionality. Fixed.

ui: Translation enabled within the tray icon context menu

---

ui/src/UI/Views/Settings/LanguageView.xaml

- Prevent tabbing to language container before language radio button

ui: make container of item in languages list not focusable

---

installer/FirefoxPrivateNetworkVPN.wxs

Previously, during an application update, the background broker service would be installed, but not started.  These changes address this issue by adding service control restart logic as well as using a new custom action to force close the application after stopping services (as opposed to the previous WiX CloseApplication element util extension).

installer: Fix start broker service on application update bug

---

test/integrations/integration_helper.go
ui/Guardian.Tests/FirefoxPrivateNetwork.Tests.csproj
ui/Guardian.Tests/ServerList/ServerSelectionTest.cs
ui/Guardian.Tests/ServerList/SortingAndRetrievalTest.cs
ui/src/FxA/ServerList/ServerList.cs
ui/src/Models/CountryServerListItem.cs
ui/src/Network/Pinger.cs
ui/src/UI/Views/ConnectionView.xaml
ui/src/UI/Views/ConnectionView.xaml.cs
ui/src/UI/Views/MainView.xaml.cs
ui/src/ViewModels/MainWindowViewModel.cs
ui/src/WCF/IService.cs
ui/src/WCF/Service.cs
ui/src/WireGuard/Connector.cs

- Remove multiple servers per city from connection list
- Select a server from the list of servers associated with the selected city according to the weight of each
- Modify existing tests for server list sorting and retrieval
- Add unit tests for server selection

ui: Modify connection server list to have one option per city

---

.circleci/config.yml
test/comment/artifact.js
test/comment/index.js
test/comment/package-lock.json
test/comment/package.json

Initially we were using a third party module to generate artifact url. However CircleCI recently updated their artifact url structure which caused the artifact url in our github comment broken. As suggested by
CircleCI, we now start using CircleCI official API to get the artifact url.

fix: update artifact url in github comment

---

test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Common/Constants.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Common/UserCommonOperation.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Common/Utils.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest.csproj
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/DeviceScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/EmailInputPage.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/MainScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/ManageAccountPage.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/NetworkSettingsScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/RegisterPage.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/ServerListScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/SettingScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/SubscriptionPage.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/SubscriptionSuccessPage.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/VerificationCodePage.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/WindowsNotificationScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Sessions/BrowserSession.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Sessions/DesktopSession.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Sessions/FirefoxPrivateVPNSession.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Tests/ConnectionTest.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Tests/NewUserSignInTest.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Tests/SettingTest.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Tests/UtilsTest.cs
test/smoke/aws/create_ec2.ps1
test/smoke/aws/template.json

We add new user login UI test. During this test, we make use of restmail as our fake email address to register fxa account. After everything is done, we remove the account from both restmail and fxa. At the same time, we remove the city verification from connection test and update the timeout for all sessions. In the meantime, we update setting UI test since the UI updated recently.

test: Add new user login UI test

---

ui/src/ProductConstants.cs

To be consistent with ios - https://github.com/mozilla-mobile/guardian-vpn-ios/commit/ddb54a20d1a4ee315158f668220aa2f0ec07fada

Remove spaces in UserAgent product name.

---

ui/src/UI/Views/MainView.xaml.cs

These changes address the bug where a language change within the
application does not immediately refresh the data context of the card
(which is required to load the new localized strings) within the main
view.

ui: Fix language change refresh in the main card

---

.circleci/config.yml
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Common/Constants.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Common/UserCommonOperation.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Common/Utils.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest.csproj
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/DeviceScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/ExportWindow.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/MainScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/ManageAccountPage.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/SubscriptionPage.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Screens/WindowsNotificationScreen.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Sessions/BaseSession.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Sessions/BrowserSession.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Sessions/DesktopSession.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Sessions/FirefoxPrivateVPNSession.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Tests/ConnectionTest.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Tests/DeviceTest.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Tests/ExistedUserSignInTest.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Tests/NewUserSignInTest.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Tests/OnboardingScreenTest.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Tests/SettingTest.cs
test/smoke/FirefoxPrivateVPNUITest/FirefoxPrivateVPNUITest/Tests/UtilsTest.cs

There is a bug which is caused by closing firefox browser. If the browser has multiple tabs, then firefox will popup a window to let user to confirm to close multi-tabs. It will fail our UI test since our
timeout is only 5 seconds. In order to pass, we extend the timeout for browser session to 10 seconds. In the meantime, we refactor the code to improve code quality.

test: fix the bug on firefox close

---

ui/src/Firefox Private Network.csproj
ui/src/FxA/Account.cs
ui/src/FxA/Avatar.cs
ui/src/Manager.cs
ui/src/UI/Components/Card/Avatar/Avatar.xaml
ui/src/UI/Components/Card/Avatar/Avatar.xaml.cs

These changes address the bug where the avatar image is being downloaded
in the UI thread, causing potential hanging.  The avatar image cache is
now refactored and the image is downloaded in a seperate task.

ui: Seperated avatar image download task from the UI thread

---

ui/src/FxA/Avatar.cs
ui/src/UI/Components/Card/Avatar/Avatar.xaml
ui/src/UI/Components/Card/Avatar/Avatar.xaml.cs

This change ensures that the user's latest avatar image URL is fetched
when the avatar user control is loaded.

ui: Refresh avatar image on load

---

ui/src/UI/Views/ConnectionView.xaml.cs
ui/src/WireGuard/Connector.cs

Since there're multiple places calling Connector#Connect(), I put MainWindowViewModel#UpdateServerSelection() directly in the Connector#Connect(), and remove the calling to it from ConnectionView#RaidoButton_Click since it will eventually be called in Connector#Connect()

Refresh selected server every time before connecting/switching

---

ui/src/FxA/Account.cs
ui/src/FxA/ApiRequest.cs
ui/src/FxA/Devices.cs

**STR**
There're several potential scenario that will cause this issue
1. Race condition between disconnect and remove-device operations
2. Network unstable
3. Device key is not dispatched yet by the remote server (connect and logout immediately after login)
**Root cause**
Device#RemoveDevice() didn't check the return value of ApiRequest#SendRequest(), which will be null if there's any network error, so a NullReferenceException is thrown outside of this method and get caught by the outer Account#Logout(). This is why the silent flag passed to this method is not respected.
**Solution**
1. Add null-check to the return value of SendRequest(), thus any failure will be handled by RemoveDevice() itself, thus the silent flag will be respected.
2. Adjust the order of disconnect and remove-device …

GUARDIAN-623: A remove device fail message is popped after logout during a vpn connection

---

.circleci/config.yml

**Reason**
1. From the history on the CI server, these smock-tests almost never passes.
2. These tests were put under the smock-test folder but were named as UI-test. After looking at the implementation, I think these tests are neither smock-test nor UI-test and are lack of clear testing scope.
> - For UI-test, these tests depend too heavily on the external environment, such as the website flow, or even the location of the test machine. 
> - For smock-test, they are too complicated and focus too much on the small matters such as the content of a displayed string.
I think we should first determine the testing scope, and properly implement them before scheduling them periodically on the CI server.

Remove smoke test

---

ui/src/FxA/Login.cs
ui/src/FxA/LoginSessionManager.cs
ui/src/Main.cs
ui/src/Properties/AssemblyInfo.cs
ui/src/UI/Views/Settings/SettingsView.xaml
ui/src/WCF/Service.cs

Fixes #144, #143, #142
This update is to fix a bug found with the way PKCE was storing the code verifier on file. It uses a localhost port instead of the mozilla-vpn uri.
This implementation also fixes issues with multiple instances of the VPN client allowed to run, needing UAC each time the client is opened, and issues with the VPN working after signing in.

Updates to PKCE configs

---

README.md

Removes locale stipulation when linking to the NuGet CLI docs.

Update link to NuGet CLI docs - Nit
